### ISSUE TITLE
请问报Internal Server Error

### ISSUE THREAD

**Issue by swiftwind0405** [justjavac/openai-proxy#12]
用的一键部署，打开出现了服务器错误，请问是什么原因呀

**Comment by Sunpulseqd** [comment]
我也是  

gcp-asia-east2NotFound: No such file or directory
    at async readFile (ext:deno_deploy/02_fs.js:56:10)
    at async Object.readTextFile (ext:deno_deploy/02_fs.js:64:15)
    at async Server.<anonymous> (https://raw.githubusercontent.com/justjavac/openai-proxy/main/main.ts:6:29)
    at async Server.#respond (https://deno.land/std@0.181.0/http/server.ts:220:24)

**Comment by justjavac** [comment]
下午我修一下

**Comment by swiftwind0405** [comment]
感谢大佬，已经可以了
