### ISSUE TITLE
请问现在还维护吗？报错了

### ISSUE THREAD

**Issue by Attiv** [justjavac/openai-proxy#33]
ypeError: No such file or directory (os error 2)
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:501:7)
    at async Server.#respond (https://deno.land/std@0.181.0/http/server.ts:299:18)

**Comment by justjavac** [comment]
有没有详细的报错信息和部署地址。我这儿一直在用，挺正常的

**Comment by Attiv** [comment]
抱歉不怎么会用。
1. 把 https://raw.githubusercontent.com/justjavac/openai-proxy/main/deno.ts 里面的内容复制到 deno playground 里
2. Save & Deploy
3. 报错：
```
gcp-us-west2TypeError: No such file or directory (os error 2)
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:501:7)
    at async Server.#respond (https://deno.land/std@0.181.0/http/server.ts:299:18)
```
部署地址是：https://fat-moth-39.deno.dev

**Comment by justjavac** [comment]
把这3行删了就可以了 https://github.com/justjavac/openai-proxy/blob/main/deno.ts#L8-L10

**Comment by wangrongding** [comment]
我也遇到了，是需要我手动添加一个 package.json？

<img width="1009" alt="image" src="https://github.com/justjavac/openai-proxy/assets/42437658/5555fc0d-0ce2-4a6b-ace8-feee0e51e664">

**Comment by justjavac** [comment]
你部署到哪儿了，这个不是 node 项目
