### ISSUE TITLE
It works yesterday. But today it error

### ISSUE THREAD

**Issue by rain2307** [justjavac/openai-proxy#37]
```
Error: 502 502: Bad Gateway (CONNECTION_BROKEN)\n\nThe deployment failed while serving the request.\n    
at W.generate (/app/.next/server/app/api/openai/chat/route.js:22:1839)\n    
at tF.makeStatusError (/app/.next/server/app/api/openai/chat/route.js:22:13240)\n    
at tF.makeRequest (/app/.next/server/app/api/openai/chat/route.js:22:13970)\n    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    
at async k (/app/.next/server/app/api/openai/chat/route.js:2:2906)\n    
at async /app/.next/server/app/api/openai/chat/route.js:7:64510"
```

昨天还好好的

**Comment by justjavac** [comment]
现在应该好了吧，我刚试了下，可以

**Comment by threeColorFr** [comment]
> 现在应该好了吧，我刚试了下，可以

刚试了下，好像还是502。而且好像不能一键部署了

**Comment by justjavac** [comment]
试试 https://fine-lion-87.deno.dev 我刚刚部署的

**Comment by threeColorFr** [comment]
https://fine-lion-87.deno.dev/v1您好大佬，刚试了openai.api_base = "https://fine-lion-87.deno.dev/v1"后使用还是502

**Comment by justjavac** [comment]
<img width="1037" alt="image" src="https://github.com/justjavac/openai-proxy/assets/359395/28390971-03de-4189-9810-f13f47b25188">
